---
- include: users.yml
  sudo: yes
  tags:
  - ec2
  - virtualbox
  - vsphere
- include: ssh.yml
  sudo: yes
  tags:
  - ec2
  - virtualbox
  - vsphere
- include: virtualbox.yml
  when: (ansible_virtualization_type == "virtualbox") and (ansible_virtualization_role == "guest")
  sudo: yes
  tags:
  - virtualbox
- name: Restart sshd (CentOS)
  service:
    name: sshd
    state: restarted
    enabled: yes
  when: (ansible_distribution == "CentOS") or (ansible_distribution == "RedHat")
- name: Restart ssh (Ubuntu)
  service:
    name: ssh
    state: restarted
    enabled: yes
  when: (ansible_distribution == "Ubuntu")
