---
- name: user exists
  user: name={{ item.name }} groups={{ item.groups }} append=yes
  with_items: "{{ users }}"
- name: ssh keys
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.pubkey }}"
    state: present
    exclusive: yes
  with_items: "{{ users }}"
