---
- include: users.yml
  sudo: yes
  tags:
  - ec2
  - virtualbox
  - vsphere
- include: ssh.yml
  sudo: yes
  tags:
  - ec2
  - virtualbox
  - vsphere
- include: virtualbox.yml
  when: (ansible_virtualization_type == "virtualbox") and (ansible_virtualization_role == "guest")
  sudo: yes
  tags:
  - virtualbox
- name: Restart sshd
  service:
    name: sshd
    state: restarted
    enabled: yes
  tags:
  - ec2
  - virtualbox
  - vsphere
