---
- name: group 'wheel' exists
  group:
    name: wheel
    state: present
    system: yes
- name: user exists
  user: name={{ item.name }} shell=/bin/bash groups={{ item.groups }} append=yes
  with_items: "{{ users }}"
- name: ssh keys
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.pubkey }}"
    state: present
    exclusive: yes
  with_items: "{{ users }}"
- name: Copy sudoers
  template:
    src: sudoers.j2
    dest: /etc/sudoers
    mode: 0400
    owner: root
    group: root
    validate: 'visudo -cf %s'
